# Régression linéaire à plusieurs variables - Exercices tirés du MOOC d'Andrew Ng

## Chargement des données

Le jeu de données donne la valeur de plusieurs maisons, ainsi que leur taille (pieds carrés) et le nombre de chambres à coucher

### Chargez les données du fichier ex1data1.csv

Before all : to re-align with the forked repo
`git remote -v`

`git remote add upstream https://github.com/42-AI/ateliers-ml-2019.git`

`git fetch upstream`

`git checkout master`

`git commit -m 'previous week s work'`

`git merge upstream/master`

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("data.csv")

### Visualisez les données (valeurs réelles)

Maintenant, nous avons deux 'features'. Voyez si elles ont le même ordre de grandeur

In [3]:
data

size  nb_bedrooms   price
0   2104            3  399900
1   1600            3  329900
2   2400            3  369000
3   1416            2  232000
4   3000            4  539900
5   1985            4  299900
6   1534            3  314900
7   1427            3  198999
8   1380            3  212000
9   1494            3  242500
10  1940            4  239999
11  2000            3  347000
12  1890            3  329999
13  4478            5  699900
14  1268            3  259900
15  2300            4  449900
16  1320            2  299900
17  1236            3  199900
18  2609            4  499998
19  3031            4  599000
20  1767            3  252900
21  1888            2  255000
22  1604            3  242900
23  1962            4  259900
24  3890            3  573900
25  1100            3  249900
26  1458            3  464500
27  2526            3  469000
28  2200            3  475000
29  2637            3  299900
30  1839            2  349900
31  1000            1  169900
32  2040            4  314900
33  3137            3  579900
34  1811            4  285900
35  1437            3  249900
36  1239            3  229900
37  2132            4  345000
38  4215            4  549000
39  2162            4  287000
40  1664            2  368500
41  2238            3  329900
42  2567            4  314000
43  1200            3  299000
44   852            2  179900
45  1852            4  299900
46  1203            3  239500

## Définissez quelques variables utiles

### Définissez X et y

X est maintenant une matrice de dimensions m x 2

In [4]:
X = np.matrix([data['size'],  data.nb_bedrooms]).T # beware size is a property of the data !!!!
y = np.matrix(data.price).T # transpose auto

In [5]:
print(X)
print(y)

[[2104    3]
 [1600    3]
 [2400    3]
 [1416    2]
 [3000    4]
 [1985    4]
 [1534    3]
 [1427    3]
 [1380    3]
 [1494    3]
 [1940    4]
 [2000    3]
 [1890    3]
 [4478    5]
 [1268    3]
 [2300    4]
 [1320    2]
 [1236    3]
 [2609    4]
 [3031    4]
 [1767    3]
 [1888    2]
 [1604    3]
 [1962    4]
 [3890    3]
 [1100    3]
 [1458    3]
 [2526    3]
 [2200    3]
 [2637    3]
 [1839    2]
 [1000    1]
 [2040    4]
 [3137    3]
 [1811    4]
 [1437    3]
 [1239    3]
 [2132    4]
 [4215    4]
 [2162    4]
 [1664    2]
 [2238    3]
 [2567    4]
 [1200    3]
 [ 852    2]
 [1852    4]
 [1203    3]]
[[399900]
 [329900]
 [369000]
 [232000]
 [539900]
 [299900]
 [314900]
 [198999]
 [212000]
 [242500]
 [239999]
 [347000]
 [329999]
 [699900]
 [259900]
 [449900]
 [299900]
 [199900]
 [499998]
 [599000]
 [252900]
 [255000]
 [242900]
 [259900]
 [573900]
 [249900]
 [464500]
 [469000]
 [475000]
 [299900]
 [349900]
 [169900]
 [314900]
 [579900]
 [285900]
 [249900]
 [229900]
 [345000]
 [549000

### Initialisez theta (combien de dimensions?)

In [6]:
theta = np.zeros(3)

### Vérifiez les dimensions de theta et de X. Sont-elles compatibles pour implémenter la fonction d'hypothèse sous forme vectorisée?

In [7]:
print(X.shape)
print(X.ndim)

(47, 2)
2


In [8]:
print(y.shape)

(47, 1)


In [9]:
print(theta.shape)

(3,)


### Modifiez X en conséquence

In [10]:
print(X.shape[1])
#XX2 = np.full(X.shape[1], 1)
#print(XX2)
#X2 = np.array([XX2, data['size'], data.nb_bedrooms]) # not the proper way but hey
#print(X2)
#X2 = np.transpose(X2)
print(X)
# alternatively
XX3 = np.ones(X.shape[0])
print(XX3)
X = np.c_[XX3, X]
print(X)
print(X.shape[0])

2
[[2104    3]
 [1600    3]
 [2400    3]
 [1416    2]
 [3000    4]
 [1985    4]
 [1534    3]
 [1427    3]
 [1380    3]
 [1494    3]
 [1940    4]
 [2000    3]
 [1890    3]
 [4478    5]
 [1268    3]
 [2300    4]
 [1320    2]
 [1236    3]
 [2609    4]
 [3031    4]
 [1767    3]
 [1888    2]
 [1604    3]
 [1962    4]
 [3890    3]
 [1100    3]
 [1458    3]
 [2526    3]
 [2200    3]
 [2637    3]
 [1839    2]
 [1000    1]
 [2040    4]
 [3137    3]
 [1811    4]
 [1437    3]
 [1239    3]
 [2132    4]
 [4215    4]
 [2162    4]
 [1664    2]
 [2238    3]
 [2567    4]
 [1200    3]
 [ 852    2]
 [1852    4]
 [1203    3]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1.000e+00 2.104e+03 3.000e+00]
 [1.000e+00 1.600e+03 3.000e+00]
 [1.000e+00 2.400e+03 3.000e+00]
 [1.000e+00 1.416e+03 2.000e+00]
 [1.000e+00 3.000e+03 4.000e+00]
 [1.000e+00 1.985e+03 4.000e+00]
 [1.000e+00 1.534e+03 3.000e+00]
 [1.000e+00

## Écrivez une fonction pour centrer et réduire les features

In [11]:
def featureScaleNormalize(X):
    # NO this is the mean of all values ! ## mean = X.mean()
    mean = np.mean(X, axis = 0)
    # NO this is the std dev of all values ! ##  stdev = X.std()
    stdev = np.std(X, axis = 0)
    # print(stdev)
    # we now need to apply it to each value
    # X = 1 if stdev.any == 0 else (X - mean)/ stdev # this won't work for first column which has a stddev of 0
    X = (X - mean)/ stdev
    return X, mean, stdev

In [12]:
X[:,1:], mean, stdev = featureScaleNormalize(X[:,1:])
print(X)

[[ 1.00000000e+00  1.31415422e-01 -2.26093368e-01]
 [ 1.00000000e+00 -5.09640698e-01 -2.26093368e-01]
 [ 1.00000000e+00  5.07908699e-01 -2.26093368e-01]
 [ 1.00000000e+00 -7.43677059e-01 -1.55439190e+00]
 [ 1.00000000e+00  1.27107075e+00  1.10220517e+00]
 [ 1.00000000e+00 -1.99450507e-02  1.10220517e+00]
 [ 1.00000000e+00 -5.93588523e-01 -2.26093368e-01]
 [ 1.00000000e+00 -7.29685755e-01 -2.26093368e-01]
 [ 1.00000000e+00 -7.89466782e-01 -2.26093368e-01]
 [ 1.00000000e+00 -6.44465993e-01 -2.26093368e-01]
 [ 1.00000000e+00 -7.71822042e-02  1.10220517e+00]
 [ 1.00000000e+00 -8.65999486e-04 -2.26093368e-01]
 [ 1.00000000e+00 -1.40779041e-01 -2.26093368e-01]
 [ 1.00000000e+00  3.15099326e+00  2.43050370e+00]
 [ 1.00000000e+00 -9.31923697e-01 -2.26093368e-01]
 [ 1.00000000e+00  3.80715024e-01  1.10220517e+00]
 [ 1.00000000e+00 -8.65782986e-01 -1.55439190e+00]
 [ 1.00000000e+00 -9.72625673e-01 -2.26093368e-01]
 [ 1.00000000e+00  7.73743478e-01  1.10220517e+00]
 [ 1.00000000e+00  1.31050078e+

### Maintenant nous allons devoir adapter nos fonctions _predict_, _fit_, et _cost_ à une situation à plusieurs variables

In [14]:
def predict(X, theta):
    #z = theta[1] * X + theta[0]
    #z = theta[0] + theta[1].x[:,] + theta[1].x[,:] 
    z = np.dot(X, theta)
    return z
print(predict(X, theta))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
X.shape[0]

47

In [ ]:
def cost(X, y, theta):
    #m = X.shape[0]
    # investigate how to do ^ 2 on a vector in python
    # v = (predict(X, theta) - y) * (predict(X, theta) - y)
    # return (1 / (2 *m) * sum(v))
    return ((1/(2 * X.shape[0])) * (np.sum((predict(X, theta) - y)**2)))
print(cost(X, y, theta))

In [ ]:
#print(np.dot((predict(X, theta) - y), X))

In [ ]:
def fit_with_cost(X, y, theta, alpha, num_iters):
    # Initialiser certaines variable utiles
    m = X.shape[0]
    J_history = np.empty(num_iters)
    theta_history = []
    # Boucler sur le nombre d'itérations
    for i in range (num_iters):
        # Effectuer une itération de descente du gradient (i.e. on update theta une fois)
        thetatmp = theta
        z = predict(X, thetatmp)
        v = z - y
        w = v * X
        theta[0] = theta[0] - alpha / m * sum (v)
        # could also be 
        #theta[0] = theta[0] - alpha / m * v.sum()
        theta[1] = theta[1] - alpha / m * sum (w)           
        J_history[i] = cost(X, y, theta)
        theta_history.extend([theta[0],theta[1]])
    return theta, J_history
    
    
    
    return theta, J_history

## Lancez l'entrainement du modèle

Vous êtes libres de choisir alpha et num_iters cette fois!

## Visualisez l'évolution du coût (graphe de convergence)

In [ ]:
fit = plt.figure()
ax = plt.axes()
ax.plot(J_history)

## Testez votre modèle

Que vaut une maison de 1650 pieds carrés et de 3 chambres à coucher? (Si la valeur est aberrante, vous avez peut-être oublié une étape...)

### Réécrivez votre fonction fit pour qu'elle prenne en compte un parametre de regularisation (L1, L2 pour Lasso ou Ridge) et adapte la mise  a jour de theta an fonction de la regularization précisée

In [ ]:
def fit_with_regularization(X, y, theta, alpha, num_iters, regularization=""):
    
    
    
    
    return theta, J_history

### La fonction fit au complet. Ajoutez un dernier parametre qui précise le gradient employé (stochastic, mini_batch(avec le batch_size), batch). Pour la descente de gradient stochastic et minibatch on met a jour le learning rate avec la formule du learning rate decay

In [ ]:
def complete_fit(X, y, theta, alpha, num_iters, regularization="", gradient_descent="batch", batch_size=4, decay_rate=1):
    
    
    
    
    return theta, J_history